version: '3'
services:
  app:
    container_name: app-laravel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: CarteiraDigital
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: laravel123
    ports:
      - "3306:3306"
