version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api-tray
    container_name: api-tray
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - default

  mysql:
    image: mysql:latest
    container_name: db-tray
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=CarteiraDigital
      - MYSQL_USER=laravel-user
      - MYSQL_PASSWORD=laravel123

    networks:
      - default